### ISSUE TITLE
Add missing apps

### ISSUE THREAD

**Issue by onbjerg** [aragon/aragon-apps#4]
Add the missing apps as they become stable

- [x] #1: Add fundraising app
- [x] #2: Add finance app
- [x] #3: Add token manager app

**Comment by izqui** [comment]
Added all apps
